# Generated by Django 4.2.5 on 2024-02-26 20:00

import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductJsonArxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('json_product', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=300)),
                ('material_nomer', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('articul', models.PositiveIntegerField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_data', models.CharField(blank=True, max_length=300, null=True)),
                ('tavar_dagavornaya', models.BooleanField(default=False)),
                ('product_status', models.BooleanField(blank=True, default=False)),
                ('seller_count', models.PositiveIntegerField(blank=True, default=0)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('full_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_video', models.FileField(blank=True, null=True, upload_to='productvideo')),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='product images')),
                ('deliver_date', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('tavar_ckidka', models.PositiveIntegerField(blank=True, null=True)),
                ('total_number', models.IntegerField(blank=True, null=True)),
                ('Umumiy_soni', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('tavar_putty', models.BooleanField(blank=True, default=False)),
                ('site_sts', models.BooleanField(blank=True, default=False)),
                ('site_rts', models.BooleanField(blank=True, default=False)),
                ('serenaTrue_countFalse', models.BooleanField(default=True)),
                ('dokon_tavarlar', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True), blank=True, null=True, size=None)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.maincategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
                ('super_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.supercategory')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ['pk', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
