# Generated by Django 4.2.5 on 2024-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tavar_ckidka',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
