# Generated by Django 4.2.5 on 2024-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_tavar_ckidka"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_jsondata", models.JSONField(blank=True, null=True)),
                ("date_createt", models.DateField(blank=True, null=True)),
                ("status_import", models.BooleanField(blank=True, default=False)),
                ("imports_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
