# Generated by Django 4.2.5 on 2024-04-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNewsImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.IntegerField(blank=True, unique=True, verbose_name='import products')),
                ('commentary', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateField(blank=True, null=True, verbose_name='create date product')),
                ('datetime_create', models.DateTimeField(blank=True, null=True)),
                ('createStatus_number', models.IntegerField(blank=True, default=0, verbose_name='number status')),
                ('products', models.JSONField(blank=True, null=True)),
                ('close_data', models.BooleanField(blank=True, default=False)),
                ('shop_id', models.UUIDField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
