# Generated by Django 5.0.6 on 2024-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productnewsimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="TavarTekshiruv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_id", models.UUIDField(blank=True, null=True)),
                ("shop_name", models.CharField(blank=True, null=True)),
                ("products", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="status bu dokondan barcha tavarlarni tekshirgan yoki tekshirmagani bildiriadi",
                    ),
                ),
                (
                    "qarzdorlik",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="qarzdorlik bo'yicha chiqmagan tavarlarni umumiy narxi",
                    ),
                ),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
