# Generated by Django 5.0.6 on 2024-06-14 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_tavartekshiruv"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSerenapathEnd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(blank=True, unique=True)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                (
                    "material_nomer",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "product_serena",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=30),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "productSerena_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True), blank=True, size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSerenapathFour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(blank=True, unique=True)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                (
                    "material_nomer",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "product_serena",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=30),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "productSerena_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True), blank=True, size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSerenapathOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(blank=True, unique=True)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                (
                    "material_nomer",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "product_serena",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=30),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "productSerena_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True), blank=True, size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSerenapathTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(blank=True, unique=True)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                (
                    "material_nomer",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "product_serena",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=30),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "productSerena_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True), blank=True, size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZerenaPathStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datatest",
                    models.CharField(
                        blank=True,
                        default="test",
                        editable=False,
                        help_text="buni o'zgartirmang",
                        verbose_name="test settings",
                    ),
                ),
                ("count_status", models.IntegerField(blank=True, default=1)),
                ("year_filter", models.IntegerField(blank=True, unique=True)),
                ("delete_bool", models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
