# Generated by Django 5.0.6 on 2024-06-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productserenapathend_productserena_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImport',
        ),
    ]
