# Generated by Django 5.0.6 on 2024-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavdoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skidka_max', models.IntegerField(blank=True, default=0, help_text="bunda foizlarda ko'rsatiladi", verbose_name='sklida foizda')),
                ('skidkaSetting', models.BooleanField(blank=True, default=False, help_text='yoqilsa settingdagi skidka foydalanish ishga tushadi ')),
                ('skidkaYoqish', models.BooleanField(blank=True, default=False, help_text='bu skidka berishni yoqish ')),
                ('tavar_skidka', models.BooleanField(blank=True, default=False, help_text='bunda tavarni skidkasi ishga tushirish')),
                ('dokonSettings_skidka', models.BooleanField(blank=True, default=False)),
                ('cashback_min', models.IntegerField(blank=True, help_text='cashback min miqdori kiritiladi', null=True, verbose_name='cashback min miqdor')),
                ('cashback_max', models.IntegerField(blank=True, help_text='client yechib oladigan max miqdor', verbose_name='cashback max miqdor')),
                ('diller_verfify', models.BooleanField(blank=True, default=False, help_text='diller royhatga olish uchun sms yuborish true yuboriladi false yuborilmaydi', verbose_name='diller register sms')),
                ('savdo_stop', models.BooleanField(blank=True, default=True, help_text="Agar true savdo amalga oshiriladi false savdo to'xtatiladi")),
                ('update_json', models.JSONField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cashbackYoqish', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
