# Generated by Django 4.2.5 on 2024-02-26 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(blank=True, max_length=50)),
                ('familya', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('ish_staj', models.CharField(blank=True, max_length=20, null=True)),
                ('xodim_band', models.BooleanField(default=False, null=True)),
                ('ishga_kelmagan', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KassaDokon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('kassa_status', models.BooleanField(blank=True, default=False)),
                ('yaratish', models.BooleanField(blank=True, default=False)),
                ('arr_dokon', models.ManyToManyField(blank=True, to='magazin.savdo')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=100)),
                ('davlatTashkilotYokiXususiy', models.BooleanField(blank=True, null=True)),
                ('inn_nomer', models.BigIntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon_nomer', models.CharField(blank=True, max_length=12, null=True)),
                ('kun_ochish', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('baza_create', models.BooleanField(blank=True, default=False)),
                ('dokon_create', models.BooleanField(blank=True, default=False)),
                ('status_servis', models.BooleanField(blank=True, default=False)),
                ('tavarlar_arrs', models.JSONField(blank=True, null=True)),
                ('dokon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dokon_id', models.UUIDField(blank=True, null=True)),
                ('summa', models.IntegerField(blank=True, null=True)),
                ('xodim_qoshish', models.ManyToManyField(blank=True, to='savdo.technicalstaff')),
            ],
        ),
    ]
