# Generated by Django 4.2.5 on 2024-04-08 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmUserModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='invalid phone number', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='pone')),
                ('ism', models.CharField(help_text='ismingizni kiriting: ', max_length=50, verbose_name='ism')),
                ('familya', models.CharField(blank=True, max_length=50, verbose_name='familya')),
                ('status_user', models.BooleanField(blank=True, default=False)),
                ('rol', models.CharField(blank=True, choices=[('SuperUser', 'SuperUser'), ('AdminUser', 'AdminUser'), ('AnalizUser', 'AnalizUser'), ('NazoratUser', 'NazoratUser'), ('GostUser', 'GostUser')], default='GostUser', max_length=25, verbose_name='user role permission')),
                ('user_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Crm foydanaluvchilar',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='XabarlarHujjatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('yuboruvchi_id', models.IntegerField(blank=True, verbose_name='yuboruvchi id')),
                ('qabulqiluvchi_id', models.IntegerField(blank=True, verbose_name='qabul qiluvchi id raqami')),
                ('read_status', models.BooleanField(blank=True, default=False, verbose_name='oqiganlik haqida status')),
                ('content', models.TextField(blank=True, null=True, verbose_name='xabar bady qism')),
                ('json_file', models.JSONField(blank=True, null=True, verbose_name='json file qism')),
                ('file', models.FileField(blank=True, help_text='doc , pdf , excell read file', null=True, upload_to='files', verbose_name='file data')),
                ('file_status', models.BooleanField(blank=True, default=False, verbose_name='file status')),
                ('fileurl', models.URLField(blank=True, null=True, verbose_name='file url')),
                ('fileupdate', models.FileField(blank=True, upload_to='files', verbose_name='update files')),
                ('fileupdate_url', models.URLField(blank=True, null=True, verbose_name='file update url')),
                ('fileupdate_status', models.BooleanField(blank=True, default=False, verbose_name='file update status')),
                ('qabulqilindi', models.BooleanField(blank=True, default=False, verbose_name='qabul qilindi status')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Xabar Hujjatlar',
                'ordering': ['pk', 'create_date', 'update_at'],
            },
        ),
        migrations.CreateModel(
            name='KunYopish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun_ochish', models.BooleanField(blank=True, default=False, verbose_name='yangi kun ochish ')),
                ('yopish', models.BooleanField(blank=True, default=False, verbose_name='Hisobotlarni yopish')),
                ('qabul_qilish', models.BooleanField(blank=True, default=False, verbose_name='qabul qilish status')),
                ('create_date', models.DateField(blank=True, unique=True, verbose_name='yangi kunni yaratish ')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('crmuser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmuser.crmusermodels')),
            ],
            options={
                'verbose_name_plural': 'Kun Yopish',
                'ordering': ['pk', 'create_at', 'update_at'],
            },
        ),
    ]
