# Generated by Django 5.0.6 on 2024-05-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoustUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(blank=True)),
                ("create_data", models.DateTimeField(auto_now=True)),
                ("online", models.BooleanField(blank=True, default=False)),
                ("userId", models.IntegerField(blank=True, null=True)),
                ("device", models.CharField(blank=True, null=True)),
                ("ipAdress", models.CharField(blank=True, null=True)),
            ],
        ),
    ]
