# Generated by Django 4.2.5 on 2024-05-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_gouseuser_hostname_gouseuser_ip_gouseuser_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userActive",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
