# Generated by Django 5.0.6 on 2024-06-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_useractive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userActive',
        ),
    ]
