# Generated by Django 4.2.5 on 2024-02-26 20:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAllPutty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_uuid', models.IntegerField(blank=True)),
                ('serenaArray', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None)),
                ('product_material', models.BigIntegerField(blank=True, null=True)),
                ('product_count', models.IntegerField(blank=True, null=True)),
                ('product_status', models.BooleanField(blank=True, default=False)),
                ('productSend_error', models.CharField(blank=True, max_length=300, null=True)),
                ('productAdd_shop', models.BooleanField(blank=True, default=False)),
                ('createDate', models.DateField(blank=True, null=True)),
                ('updateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TavarPutty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_maagzinId', models.UUIDField(blank=True, null=True)),
                ('product_status', models.BooleanField(blank=True, default=False)),
                ('comentary', models.CharField(blank=True, max_length=300, null=True)),
                ('putty_status', models.BooleanField(blank=True, default=False)),
                ('qabul', models.BooleanField(blank=True, default=False)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('putty_delete', models.BooleanField(blank=True, default=False)),
                ('tavarlar', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True), blank=True, null=True, size=None)),
                ('productsId', models.ManyToManyField(blank=True, to='puttyMagazin.productallputty')),
                ('shopId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.allshop')),
            ],
            options={
                'verbose_name_plural': 'TavarPutty',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DokonPutty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BooleanField(blank=True, default=False, null=True)),
                ('vendor_tavarlar', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True), blank=True, null=True, size=None)),
                ('dokon_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.allshop')),
            ],
        ),
    ]
