# Generated by Django 4.2.5 on 2024-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puttyMagazin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakasProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(blank=True)),
                ('qabul', models.BooleanField(blank=True, default=False)),
                ('shop_id', models.UUIDField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
