# Generated by Django 4.2.5 on 2024-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puttyMagazin', '0002_zakasproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakasproduct',
            name='nomer_zakas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
