# Generated by Django 4.2.5 on 2024-05-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puttyMagazin", "0004_zakasproduct_date_filter_zakasproduct_shop_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tavarputty",
            name="zakasproductstatus",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
