# Generated by Django 5.0.6 on 2024-06-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puttyMagazin', '0005_tavarputty_zakasproductstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavarputty',
            name='productsId',
        ),
        migrations.DeleteModel(
            name='ProductAllPutty',
        ),
    ]
