# Generated by Django 5.0.6 on 2024-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puttyMagazin', '0006_remove_tavarputty_productsid_delete_productallputty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokonputty',
            name='vendor_tavarlar',
        ),
        migrations.AddField(
            model_name='dokonputty',
            name='tavarlar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
