# Generated by Django 4.2.5 on 2024-02-26 20:00

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllShop',
            fields=[
                ('tavarPuttyID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foydalanuvchi_ism', models.CharField(blank=True, max_length=100, null=True)),
                ('foydalanuvchi_familya', models.CharField(blank=True, max_length=100, null=True)),
                ('dokon_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('dokon_url', models.URLField(blank=True, null=True)),
                ('dokon_image', models.ImageField(blank=True, null=True, upload_to='dokonImage')),
                ('shop_status', models.BooleanField(blank=True, default=False)),
                ('zakas_site', models.BooleanField(blank=True, default=False)),
                ('tavar_putty', models.BooleanField(blank=True, default=False)),
                ('passwords', models.CharField(blank=True, max_length=100, null=True)),
                ('sklad', models.BooleanField(blank=True, default=False, null=True)),
                ('vendor', models.BooleanField(blank=True, default=False)),
                ('dokon_long', models.FloatField(blank=True, null=True)),
                ('dokon_lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Barcha dokonlar',
                'ordering': ['pk', 'foydalanuvchi_ism'],
            },
        ),
        migrations.CreateModel(
            name='CommentaryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('comment_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaySellerShop',
            fields=[
                ('daySavdo_nomer', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('savdo_uuid', models.UUIDField(blank=True, null=True)),
                ('savdo_yopish', models.BooleanField(blank=True, default=False)),
                ('cashback_sum', models.PositiveIntegerField(blank=True, default=0)),
                ('sellerdate_create', models.DateField(blank=True, null=True)),
                ('sellerclose_date', models.DateTimeField(blank=True, null=True)),
                ('tolangan_sum', models.BigIntegerField(blank=True, null=True)),
                ('qarzdorlik_summa', models.BigIntegerField(blank=True, null=True)),
                ('toliqQarzga', models.BooleanField(blank=True, default=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('product_arr', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True), blank=True, null=True, size=None)),
                ('datetime_create', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('skidka_price', models.PositiveIntegerField(blank=True, null=True)),
                ('depozit_sum', models.PositiveIntegerField(blank=True, null=True)),
                ('tavarUmmiy_summasi', models.PositiveIntegerField(blank=True, default=0)),
                ('clientdan_olganSumma', models.PositiveIntegerField(blank=True, null=True)),
                ('savdo_naxtga', models.BooleanField(blank=True, default=False)),
                ('savdo_plastik', models.BooleanField(blank=True, default=False)),
                ('joyida_tolov', models.BooleanField(blank=True, default=False)),
                ('shartnoma', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NastroykaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savdo_all', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShartNoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BooleanField(blank=True, default=False)),
                ('sharnoma_nomer', models.IntegerField(blank=True, null=True)),
                ('arganization_name', models.CharField(blank=True, max_length=300)),
                ('inn_code', models.BigIntegerField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='shartnoma')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('savdo_id', models.UUIDField(blank=True, null=True)),
                ('tolangan_summa', models.BigIntegerField(blank=True, null=True)),
                ('qarzdorlik_sum', models.BigIntegerField(blank=True, null=True)),
                ('birja_request', models.BooleanField(blank=True, default=False)),
                ('request_money', models.BooleanField(default=False)),
                ('closes', models.BooleanField(blank=True, default=False)),
                ('data_create', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('product_array', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TashkilotYaratish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tashkilot_nomi', models.CharField(blank=True, max_length=100)),
                ('telefon_raqam', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('inn_raqam', models.BigIntegerField(blank=True, null=True)),
                ('shartnoma_file', models.FileField(blank=True, null=True, upload_to='shartnomalar')),
                ('dagavor', models.FileField(blank=True, null=True, upload_to='dagavorlar')),
                ('organzation_status', models.CharField(blank=True, choices=[('Shartnoma qilindi', 'Shartnoma qilindi'), ('shartnoma yuborildi', 'shartnoma yuborildi'), ('bugaltera file yuborildi', 'bugaltera file yuborildi'), ('pul tushdi', 'pul tushdi')], default='Shartnoma qilindi', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('savdolUID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daySalesDate_create', models.DateField(blank=True, unique=True)),
                ('daySalesCloseDate', models.DateTimeField(blank=True, null=True)),
                ('savdo_status', models.BooleanField(blank=True, default=False)),
                ('kunlik_chiqim', models.PositiveIntegerField(blank=True, null=True)),
                ('comentary', models.TextField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('savdo_yopish', models.BooleanField(blank=True, default=False)),
                ('kassa_qabul', models.BooleanField(blank=True, default=False)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
                ('savdo_files', models.FileField(blank=True, null=True, upload_to='savdo')),
                ('camentary_choise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.commentarystatus')),
                ('createdateseller', models.ManyToManyField(blank=True, to='magazin.daysellershop')),
                ('dokon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.allshop')),
                ('shartnoma_create', models.ManyToManyField(blank=True, to='magazin.shartnoma')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^998\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='password/images/')),
                ('passportLocation_image', models.ImageField(blank=True, null=True, upload_to='password/images/')),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('savdo_sum', models.BigIntegerField(blank=True, default=0)),
                ('cashback_register', models.BooleanField(blank=True, default=False)),
                ('foiz', models.PositiveIntegerField(blank=True, null=True)),
                ('status_client', models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Medium', 'Medium'), ('Advanced', 'Advanced'), ('special', 'Special')], default='Simple', max_length=30, null=True)),
                ('organzation_status', models.CharField(blank=True, choices=[('Shartnoma qilindi', 'Shartnoma qilindi'), ('shartnoma yuborildi', 'shartnoma yuborildi'), ('bugaltera file yuborildi', 'bugaltera file yuborildi'), ('pul tushdi', 'pul tushdi')], default='Shartnoma qilindi', max_length=30, null=True)),
                ('client_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='daysellershop',
            name='client_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.klient'),
        ),
        migrations.AddField(
            model_name='daysellershop',
            name='tashkilot_qoshish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.tashkilotyaratish'),
        ),
        migrations.AddField(
            model_name='allshop',
            name='dokon_client',
            field=models.ManyToManyField(blank=True, to='magazin.klient'),
        ),
        migrations.AddField(
            model_name='allshop',
            name='nastroyka',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazin.nastroykamodel'),
        ),
        migrations.AddField(
            model_name='allshop',
            name='userId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
