# Generated by Django 4.2.5 on 2024-04-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_klient_customer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='organzation_status',
        ),
    ]
