# Generated by Django 4.2.5 on 2024-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_remove_klient_organzation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='foydalanuvchi_turi',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
