# Generated by Django 5.0.6 on 2024-05-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magazin", "0005_klient_foydalanuvchi_turi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daysellershop",
            name="tolangan_sum",
        ),
    ]
