# Generated by Django 5.0.6 on 2024-05-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazin", "0006_remove_daysellershop_tolangan_sum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysellershop",
            name="clientdan_olganSumma",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="daysellershop",
            name="qarzdorlik_summa",
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
