# Generated by Django 5.0.6 on 2024-06-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0007_alter_daysellershop_clientdan_olgansumma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysellershop',
            name='datetime_create',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='sellerclose_date',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='toliqQarzga',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='update_date',
        ),
        migrations.AddField(
            model_name='daysellershop',
            name='year_filter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
