# Generated by Django 5.0.6 on 2024-06-18 07:41

import magazin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_remove_daysellershop_datetime_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysellershop',
            name='cashback_sum',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='clientdan_olganSumma',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='depozit_sum',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='joyida_tolov',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='qarzdorlik_summa',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='savdo_naxtga',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='savdo_plastik',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='shartnoma',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='skidka_price',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='tashkilot_qoshish',
        ),
        migrations.RemoveField(
            model_name='daysellershop',
            name='tavarUmmiy_summasi',
        ),
        migrations.AddField(
            model_name='daysellershop',
            name='savdo_detail',
            field=models.JSONField(blank=True, default=magazin.models.get_savdo_status),
        ),
    ]
