# Generated by Django 5.0.6 on 2024-06-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0009_remove_daysellershop_cashback_sum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savdo',
            name='savdo_files',
        ),
        migrations.RemoveField(
            model_name='savdo',
            name='savdolUID',
        ),
        migrations.RemoveField(
            model_name='savdo',
            name='update_datetime',
        ),
    ]
