# Generated by Django 5.0.6 on 2024-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0011_alter_allshop_nastroyka_alter_allshop_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nastroykamodel',
            name='skidka',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
