# Generated by Django 5.0.6 on 2024-06-24 07:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0012_nastroykamodel_skidka'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='hisobraqam_article',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
