# Generated by Django 4.2.5 on 2023-09-25 07:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Istoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
