# Generated by Django 4.2.5 on 2024-02-26 19:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepozitCarddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depozit_kard', models.BigIntegerField(blank=True, null=True)),
                ('depozit_sum', models.PositiveIntegerField(blank=True, default=0)),
                ('depozit_random', models.BooleanField(blank=True, default=False)),
                ('activate_depozit', models.BooleanField(blank=True, default=False)),
                ('depozit_arxiv', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kard_cod', models.BigIntegerField(blank=True, null=True)),
                ('activae_kard', models.BooleanField(blank=True, default=False)),
                ('karta_sum', models.PositiveIntegerField(blank=True, default=0)),
                ('karta_random', models.BooleanField(blank=True, default=False)),
                ('kardSumma_arxiv', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'kard',
                'ordering': ['pk', 'kard_cod'],
            },
        ),
        migrations.CreateModel(
            name='Hamyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuidfiled', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False)),
                ('money', models.PositiveIntegerField(blank=True, default=0)),
                ('activete', models.BooleanField(blank=True, default=False)),
                ('karta_date', models.DateTimeField(auto_now_add=True)),
                ('depozitcardId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.depozitcarddata')),
                ('kard', models.ManyToManyField(blank=True, to='cash.kard')),
            ],
        ),
    ]
